---
# tasks file for expose

- name: Install nginx if not present
  apt:
    name: nginx
    state: present
    install_recommends: yes

- name: Install certbot if not present
  apt:
    name: certbot
    state: present
    install_recommends: yes

- name: Install python3-certbot-nginx if not present
  apt:
    name: python3-certbot-nginx
    state: present
    install_recommends: yes

- name: Make sure a nginx service is running
  ansible.builtin.systemd:
    state: started
    name: nginx

- name: Copy nginx configuration to host in /etc/nginx/sites-available/ folder
  become: true
  copy:
    src: "{{ nginx_conf }}"
    dest: /etc/nginx/sites-available/
    group: "{{ vms_remote_user }}"
    owner: "{{ vms_remote_user }}"
    mode: "0777"

- name: Symlink nginx configuration file to /etc/nginx/sites-enabled/
  become: true
  shell: ln -sf /etc/nginx/sites-available/* /etc/nginx/sites-enabled/

- name: Confirm the configuration does not contain any syntax errors
  become: true
  shell: nginx -t

- name: Restart service nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Generate site SSL certificates using certbot
  become: true
  shell: certbot --nginx --noninteractive --agree-tos -m "{{ email_address }}" --no-redirect --keep-until-expiring -d "{{ domain_name }}"
