---
- hosts: backend
  gather_facts: false
  become: true
  pre_tasks:
    - name: "Make sure remote system is initialized correctly"
      raw: "ln -s /usr/bin/python3 /usr/bin/python"
      register: set_symlink
      failed_when: set_symlink.rc != 0 and set_symlink.rc != 1

  roles:
    - role: initialize
    - role: project_copy
      vars:
        destination_folder: /app/
    - role: expose
      vars:
        email_address: antoine.le-guillou@epitech.eu
        domain_name: nsa-server.students-epitech.ovh

  tasks:
    - name: install software-properties-common
      apt:
        name: software-properties-common
        state: latest

    - name: Add ppa:ondrej/php repository into sources list
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: update repository index
      apt:
        update_cache: true

    - name: install php7.4
      apt:
        name: php7.4
        state: present

    - name: install curl
      apt:
        name: curl
        state: present

    - name: install php-fpm
      apt:
        name: php7.4-fpm
        state: present

    - name: install php-curl
      apt:
        name: php7.4-curl
        state: present

    - name: install mbstring
      apt:
        name: php7.4-mbstring
        state: present

    - name: install php-xml
      apt:
        name: php7.4-xml
        state: present

    - name: install php-json
      apt:
        name: php7.4-json
        state: present

    - name: install php-zip
      apt:
        name: php7.4-zip
        state: present

    - name: install php-mysql
      apt:
        name: php7.4-mysql
        state: present

    - name: ensure php 7.4 is used by the system
      become: true
      shell: update-alternatives --set php /usr/bin/php7.4

    - name: Download and install Composer
      shell: curl -sS https://getcomposer.org/installer | php
      args:
        chdir: /usr/src/
        creates: /usr/local/bin/composer
      become: true

    - name: Add Composer to global path
      copy:
        src: /usr/src/composer.phar
        dest: /usr/local/bin/composer
        remote_src: true
        group: root
        mode: "0755"
        owner: root
      become: true

    - name: Installing php project dependencies
      become: true
      become_user: "{{ vms_remote_user }}"
      shell: cd /app/back && composer install

    - name: Updating php project dependencies (composer.lock file)
      become: true
      become_user: "{{ vms_remote_user }}"
      shell: cd /app/back && composer update

    - name: Copy over environnement variables.
      become: true
      become_user: "{{ vms_remote_user }}"
      shell: cd /app/back && cp .env.example .env

    - name: Generate an application key.
      become: true
      become_user: "{{ vms_remote_user }}"
      shell: cd /app/back && php artisan key:generate

    - name: Re-cache.
      become: true
      become_user: "{{ vms_remote_user }}"
      shell: cd /app/back && php artisan config:cache

    - name: Run database migrations.
      become: true
      become_user: "{{ vms_remote_user }}"
      shell: cd /app/back && php artisan migrate

    - name: Run database seed
      become: true
      become_user: "{{ vms_remote_user }}"
      shell: cd /app/back && php artisan db:seed

    - name: Make sure apache service is stopped
      become: true
      shell: apachectl stop

    - name: Restart service php7.4-fpm
      ansible.builtin.service:
        name: php7.4-fpm
        state: restarted
