---
- hosts: backend
  gather_facts: false
  become: true
  pre_tasks:
    - name: "Make sure remote system is initialized correctly"
      raw: "ln -s /usr/bin/python3 /usr/bin/python"
      register: set_symlink
      failed_when: set_symlink.rc != 0 and set_symlink.rc != 1

  tasks:
    - name: update repository index
      apt:
        update_cache: true

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

    - name: install software-properties-common
      apt:
        name: software-properties-common
        state: latest

    - name: Add ppa:ondrej/php repository into sources list
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php

    - name: update repository index
      apt:
        update_cache: true

    - name: install php7.4
      apt:
        name: php7.4

    - name: install curl
      apt:
        name: curl

    - name: install git
      apt:
        name: git

    - name: Download and install Composer
      shell: curl -sS https://getcomposer.org/installer | php
      args:
        chdir: /usr/src/
        creates: /usr/local/bin/composer
      become: true

    - name: Add Composer to global path
      copy:
        src: /usr/src/composer.phar
        dest: /usr/local/bin/composer
        remote_src: true
        group: root
        mode: "0755"
        owner: root
      become: true

    - name: copying backend project files
      become: true
      copy:
        src: "{{ project_dir }}"
        dest: /app/
        group: root
        owner: root
        mode: "0755"

    - name: Installing php project dependencies
      shell: cd /app/ && composer install

    - name: Updating php project dependencies (composer.lock file)
      shell: cd /app/ && composer update

    # - name: Installing Node JS dependencies
    #   shell: cd /app/ && npm install

    - name: Copy over environnement variables.
      shell: cd /app/ && cp .env.example .env

    - name: "Generate an application key."
      shell: cd /app/ && php artisan key:generate

    - name: Re-cache.
      shell: cd /app/ && php artisan config:cache

    - name: Run database migrations.
      shell: cd /app/ && php artisan migrate

    - name: Run database seed
      shell: cd /app/ && php artisan db:seed
